### ISSUE TITLE
Does not work with committed changes

### ISSUE THREAD

**Issue by doppleware** [QualiSystemsLab/colony-cli#21]
STR:
Make local changes
Stage
Commit 
run colony bp validate

Error:
failed due to: exit code(1)
  cmdline: git stash apply
  stderr: 'No stash entries found.'

Expected behavior:
still create remote branch with local changes no stash

**Comment by qualidan** [comment]
excellent catch...!

Changed to check before stash:

        if repo.is_dirty() or repo.untracked_files:
            stash_local_changes_and_preserve_uncommitted_code(repo)

**Comment by doppleware** [comment]
Seems to work now

**Comment by doppleware** [comment]
Situation seems WORSE now. 
It fails and also gets stuck on the wrong branch.
Please see below flow:


PS C:\Users\ronid\projects\clitest> git status
On branch master
Changes to be committed:
  (use "git restore --staged <file>..." to unstage)
        new file:   applications/java-spring-website/test.sh
        new file:   applications/new-app/new-app.yaml

PS C:\Users\ronid\projects\clitest> colony bp validate test
Automatically detected current working branch: master
Using your local blueprint changes (including uncommitted changes and/or untracked files)
Valid
PS C:\Users\ronid\projects\clitest> git add .
PS C:\Users\ronid\projects\clitest> git commit -m "update"
[master a8d44d6] update
 2 files changed, 0 insertions(+), 0 deletions(-)
 create mode 100644 applications/java-spring-website/test.sh
 create mode 100644 applications/new-app/new-app.yaml
PS C:\Users\ronid\projects\clitest> git status
On branch master
nothing to commit, working tree clean
PS C:\Users\ronid\projects\clitest> colony bp validate test
Automatically detected current working branch: master
WARNING - colony.branch_utils - Was not able push your latest changes to temp branch for validation. Reason: Cmd('git') failed due to: exit code(1)
  cmdline: git commit -m Uncommitted temp branch - temp commit for validation
  stdout: 'On branch tmp-colony-master-pxnwjzlelm
nothing to commit, working tree clean'
ERROR - colony.commands.bp - Validation failed
Name                             Message
-------------------------------  -------------------------------------------------------------------------------
Blueprint unknown cloud account  Cloud account: azure 4 is not recognized as a valid cloud account in this space

**Comment by doppleware** [comment]
issue number two has not been resolved.
On error I sometimes stay on the temp branch.
Example: have invalid login to Git:

doppleware@QS-US-LT-RONI:/mnt/c/Users/ronid/projects/clitest$ colony bp validate test
Automatically detected current working branch: tmp-colony-master-jcocysidmd
Username for 'https://github.com':
Password for 'https://github.com':
WARNING - colony.branch_utils - Was not able push your latest changes to temp branch for validation. Reason: Cmd('git') failed due to: exit code(128)
  cmdline: git push origin tmp-colony-tmp-colony-master-jcocysidmd-ceymqsvobr
  stderr: 'remote: No anonymous write access.
fatal: Authentication failed for 'https://github.com/doppleware/testyaml/''
ERROR - colony.commands.bp - Blueprint not found: The blueprint test was not found
doppleware@QS-US-LT-RONI:/mnt/c/Users/ronid/projects/clitest$ git status
On branch **tmp-colony-tmp-colony-master-jcocysidmd-ceymqsvobr**
nothing to commit, working tree clean

**Comment by doppleware** [comment]
okay the issue is also not fixed.
When I try to validate a bp with no untracked changes I get an error.
Guys what's going on?

doppleware@QS-US-LT-RONI:/mnt/c/Users/ronid/projects/clitest$ colony bp validate test
Automatically detected current working branch: master
Enter passphrase for key '/home/doppleware/.ssh/id_rsa':
Using your local blueprint changes (including uncommitted changes and/or untracked files)
Traceback (most recent call last):
  File "/home/doppleware/.local/bin/colony", line 8, in <module>
    sys.exit(main())
  File "/home/doppleware/.local/lib/python3.8/site-packages/colony/shell.py", line 96, in main
    command.execute()
  File "/home/doppleware/.local/lib/python3.8/site-packages/colony/commands/base.py", line 38, in execute
    actions_table[action]()
  File "/home/doppleware/.local/lib/python3.8/site-packages/colony/commands/bp.py", line 57, in do_validate
    revert_from_temp_branch(repo, working_branch)
  File "/home/doppleware/.local/lib/python3.8/site-packages/colony/branch_utils.py", line 153, in revert_from_temp_branch
    raise e
  File "/home/doppleware/.local/lib/python3.8/site-packages/colony/branch_utils.py", line 151, in revert_from_temp_branch
    revert_from_uncommitted_code(repo)
  File "/home/doppleware/.local/lib/python3.8/site-packages/colony/branch_utils.py", line 158, in revert_from_uncommitted_code
    repo.git.stash("pop")
  File "/home/doppleware/.local/lib/python3.8/site-packages/git/cmd.py", line 542, in <lambda>
    return lambda *args, **kwargs: self._call_process(name, *args, **kwargs)
  File "/home/doppleware/.local/lib/python3.8/site-packages/git/cmd.py", line 1006, in _call_process
    return self.execute(call, **exec_kwargs)
  File "/home/doppleware/.local/lib/python3.8/site-packages/git/cmd.py", line 823, in execute
    raise GitCommandError(command, status, stderr_value, stdout_value)
git.exc.GitCommandError: Cmd('git') failed due to: exit code(1)
  cmdline: git stash pop
  stderr: 'No stash entries found.'

**Comment by qualidan** [comment]
The first issue mentioned regarding the blueprint not found:
This was due to missing revert in the case of an exception of the validation which is now fixed
        except Exception as e:
            logger.exception(e, exc_info=False)
            bp = None
            -->revert_and_delete_temp_branch(repo, working_branch, temp_working_branch)
            self.die()

**Comment by qualidan** [comment]
regarding second issue mentioned: a check was made not to stash in case of committed or no untracked
but the revert was missing same check...now added:

def revert_from_temp_branch(repo: BlueprintRepo, active_branch) -> None:
    try:
        checkout_remote_branch(repo, active_branch)
        --->if repo.is_dirty() or repo.untracked_files:
            revert_from_uncommitted_code(repo)
