### ISSUE TITLE
Remove warnings

### ISSUE THREAD

**Issue by doppleware** [QualiSystemsLab/colony-cli#22]
"Your local branch is not synced with remote"
"You have uncommitted changes"
"Your local branch is not synced with remote"

Are not warnings - this is normal operations. 
Please reword to - "Using your local branch blueprint (including uncommitted changes)"

 Please also remove: 
"Using temp branch: tmp-colony-master-jsrlmrnjnz (This shall include any uncommitted changes and untracked files)"
Also I don't think we include any untracked files + we shouldn't provide the temp branch name

**Comment by qualidan** [comment]
1) @ddovbii - Please justify/change the warnings
2) @doppleware - we do include untracked files - and why shouldn`t we provide the branch name ? (let`s discuss this)

**Comment by alexazarh** [comment]
Lets make sure that we still print the temp branch name in debug mode
I suggest the following message wording:
"Using your local blueprint changes (including uncommitted changes and untracked files)"

**Comment by alexazarh** [comment]
Any warning still needs to be visible in debug mode

**Comment by qualidan** [comment]
fixed

**Comment by ddovbii** [comment]
why do want guys to ignore untracked files?

**Comment by doppleware** [comment]
They seem to interfere with our stash pop operation and we don't wan to do
something invasive like git clean

**Comment by qualidan** [comment]
they are back (as if we do not stash them they are deleted)
