### ISSUE TITLE
Change sandbox name convention

### ISSUE THREAD

**Issue by doppleware** [QualiSystemsLab/colony-cli#24]
Current format is [blueprint][Date-Time[

Please change to either [blueprint][-localchanges-][Datetime]
or [blueprint][-remotebranchname][Datetime] 

Depending on where we're launching from.
Also if we can change the date time format from: Mar112021-21:01:26 to 0311-21:01:26

**Comment by qualidan** [comment]
If I understood correctly if you are not working in a git Repo the remote branch is unknown and not specified Colony figures it out based on the blueprint ... but is there an API to retrieve it ?

This is what I have a solution in the meanwhile:

branch_name_or_type = "colony-defined-branch"
            if working_branch:
                branch_name_or_type = working_branch
            if temp_working_branch:
                branch_name_or_type = "localchanges"
            name = f"{blueprint_name}-{branch_name_or_type}-{suffix}"

**Comment by qualidan** [comment]
fixed
